spring:
  data:
    mongodb:
      host: 192.168.206.100
      port: 27017
      database: PMRecommender
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

server:
  port: 8081
